plugins:
  - jest
  - 'fp'
env:
  es6: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [ 2, { "allow": [ "__filename", "__dirname" ] } ]
  fp/no-arguments: "error"
  fp/no-class: "error"
  fp/no-delete: "error"
  fp/no-events: "error"
  fp/no-get-set: "error"
  fp/no-let: "error"
  fp/no-loops: "error"
  fp/no-mutating-assign: "error"
  fp/no-mutating-methods: "error"
  fp/no-mutation: "error"
  fp/no-proxy: "error"
  fp/no-rest-parameters: "error"
  fp/no-this: "error"
  fp/no-valueof-field: "error"